stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  timeout: 3 hours 30 minutes

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build
  timeout: 3h 30m

sonarqube-check:
  stage: test
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  #    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonarqube
  allow_failure: true
  only:
    - master #Run only master branch
