stages:
  - build
  - test
  - sonarqube-check
  - build_image

build:
  stage: build
  script:
    - ./gradlew assemble
  timeout: 3 hours 30 minutes

build_image:
  stage: build_image
  script:
    - docker build --build-arg JAR_FILE=build/libs/\*.jar -t springio/gs-spring-boot-docker .
    - docker run -d -p 8080:8080 springio/gs-spring-boot-docker

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  #    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script: ./gradlew sonarqube
  allow_failure: true

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build
  timeout: 3h 30m
