stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assemble
  timeout: 3 hours 30 minutes

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build
  timeout: 3h 30m
