stages:
  - build
  - test
  - sonarqube-check
  - build_image

build:
  stage: build
  script:
    - ./gradlew assemble
  timeout: 3 hours 30 minutes

build_image:
  stage: build_image
  script:
    - ./gradlew assemble
    - docker stop musicplanet
    - docker rm musicplanet
    - docker build --build-arg JAR_FILE=build/libs/MusicPlanet_API-1.0-SNAPSHOT.jar -t musicplanet_deploy .
    - docker run -d -p 8080:8080 --name musicplanet musicplanet_deploy

sonarqube-check:
  stage: sonarqube-check
  image: gradle:jre11-slim
  script: gradlew sonarqube -Dsonar.login=ba1579352b36ba1b63bb2cbd9a98e250cd38fd94 -Dsonar.projectKey=MusicPlanet_API -Dsonar.host.url=http://localhost:9000
  allow_failure: true

test:
  stage: test
  script:
    - ./gradlew test
  dependencies:
    - build
  timeout: 3h 30m
